server:
  port: 9000
  servlet:
    session:
      cookie:
        name: JSESSIONID  # **Aynı session çerezini kullan**
        #same-site: none  # **Üçüncü taraf çerezlere izin ver**
        secure: false  # **HTTPS kullanıyorsan bunu aç (Lokal test için kapat)**

spring:
  session:
    store-type: redis
    redis:
      namespace: sso-dashboard-session
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
  security:
    oauth2:
      authorizationserver:
        issuer:  https://a867-176-240-136-21.ngrok-free.app
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password: LFB2023!!q
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework:
      security: TRACE
      session: DEBUG
      data:
        redis: INFO
