server:
  port: 9000

spring:
  security:
    oauth2:
      authorizationserver:
        issuer:  https://245e-176-240-136-21.ngrok-free.app
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password: LFB2023!!q
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: DEBUG
