spring:
  security:
    saml2:
      identity-provider:
        metadata-uri: https://accounts.google.com/saml2/idp (Google IDP metadata URL)
        entity-id: YOUR_IDP_ENTITY_ID
        signing-certificate: classpath:your-signing-cert.crt
        private-key: classpath:your-private-key.key
      service-provider:
        entity-id: YOUR_SSO_DASHBOARD_ENTITY_ID
        metadata-uri: classpath:saml2-sp-metadata.xml
        signing-certificate: classpath:sp-signing-cert.crt
