server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: postgres
    password: LFB2023!!q
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          sso-dashboard-client:
            provider: custom-provider
            client-id: sso-dashboard-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/sso-dashboard-client"
            scope: openid, profile, email
        provider:
          custom-provider:
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: email
          custom-auth-server:
            issuer-uri: http://localhost:9000
