server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2
    username: poc_user
    password: poc_password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-id: Ov23liNxSW9NHjbjR6qO  # GitHub'dan aldığınız client_id
            client-secret: 5882f7951ec448cb51691035a2eda433e8417b17  # GitHub'dan aldığınız client_secret
            client-name: oauth-github
            scope: read:user,user:email # GitHub API'sine hangi izinleri alacağınızı belirleyin
            redirect-uri: "https://aeeb-176-240-136-21.ngrok-free.app/login/oauth2/code/github"
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
          spring:
            issuer-uri: http://localhost:9000


